server:
  port: 8099

spring:
  application:
    name: consumer

  cloud:
    function:
      definition: processRiderLocation

    stream:
      bindings:
        processRiderLocation-in-0:
          destination: my-topic
          content-type: application/json

      kafka:
        binder:
          brokers: localhost:9092
