server:
  port: 8088

spring:
  application:
    name: producer

  cloud:
    function:
      definition: sendRiderLocation

    stream:
      bindings:
        sendRiderLocation-out-0:
          destination: my-topic
          content-type: application/json

      poller:
        fixed-delay: 5000

      kafka:
        binder:
          brokers: localhost:9092
